    name: my first workflow
    # git hub triggers
    on:
        workflow_dispatch:
        push:
            branches:
                - main
        pull_request:
            branches:
                - main
        schedule:
            - cron: '0 5 * * 1-5'
    
    jobs:
        build:
            runs-on: ubuntu-latest
            steps:
                - name: Checkout repository 
                  uses: actions/checkout@v2
                
                - name: Use Node.js
                  uses: actions/setup-node@v3
                  with:
                      node-version: latest
                
                - name: Install dependencies
                  run: npm install

                - name: Run tests
                  run: npm test
                
                - name: Print a message
                  run: echo "Hello, World!"
