    name: my first workflow

    on:
        push:
            branches:
                - main
    
    jobs:
        build:
            runs-on: ubuntu-latest
            steps:
                - name: Checkout repository 
                  uses: actions/checkout@v2
                
                - name: Use Node.js 18
                  uses: actions/setup-node@v3
                  with:
                      node-version: 18
                
                - name: Print a message
                  run: echo "Hello, World!"
